version: '3'

services:
  terminal_vue:
    build: .
    volumes:
      - ./app/src:/app/src
      - ./app/webpack.config.js:/app/webpack.config.js
      - ./app/webpack.prod.js:/app/webpack.prod.js
      - ./dist:/app/dist
    command: >
      sh -c "npm run serve"
    ports:
      - "9000:9000"
