version: '3'

services:
  npm_termgame:
    build: .
    volumes:
      - ./app/src:/app/src
      - ./app/webpack.config.js:/app/webpack.config.js
    command: >
      sh -c "npm run build && 
             npm run start:dev"
    ports:
      - "9000:9000"
