version: '3'

services:
  terminal_vue:
    build:
      context: .
    volumes:
      - ./vue:/app
      - ./dist:/app/dist
      - modules:/app/node_modules
    command: >
      sh -c "npm run serve"
    ports:
      - 8888:8080

volumes:
  modules: {}
