version: '3'

services:
  terminal_vue:
    build:
      context: .
    volumes:
      - ./vue/src:/app/src
      - ./dist:/app/dist
    command: >
      sh -c "npm run serve"
    ports:
      - 8080:8080

