name: Skaben Konsole Static Builder

on:
  push:
    branches: [ main, test_actions ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      work-dir: ./app
      dist-dir: ./dist

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ${{ env.work-dir }}

    - run: npm run build-prod
      working-directory: ${{ env.work-dir }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ${{ env.dist-dir }}
        working-directory: ${{ env.work-dir }}
